events {}

http {
    server {
        listen 80;

        location / {
            # Проксируем запросы на сервис с именем 'app' (как в docker-compose)
            # Порт 5000 - это порт, на котором работает Flask внутри контейнера
            proxy_pass http://app:5000;
        }
    }
}
